name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run build

      - name: Comment Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issue_number,
              body: `✨ Passed local build`
            });
